### ISSUE TITLE
Bro Have u checked the accuracy may i know how to check to buy or sell the stock 

### ISSUE THREAD

**Issue by raviyellani** [louisvathan/NSE-Stocks-Strategies-Tester#4]

**Comment by louisvathan** [comment]
Working on some changes in the code. Will add user guide soon.

**Comment by louisvathan** [comment]
Hi,

**Comment by louisvathan** [comment]
Hi,
Please refer to the updated Readme file. Detailed user guide added in it. Regarding the accuracy, the calculations for strategy and backtesting are accurate. But I am taking no responsibility for any losses you incur using this program. Please check the Terms and Conditions before using the program.

Hope this answers your question. 

Thank you.
